### PR TITLE
98. Questions.md: fix formatting

### PR DESCRIPTION
**Pull request by BratishkaErik**
Before:

Screenshot_20230924_212051

After:

Screenshot_20230924_212116

### CODE REVIEW

**Comment by ZigC-Lang** [comment]
Hi! Erik,

Thanks for your interest.
This project is now at the earliest imagination stage, and everything can
be changed or even abandonned. Please, keep that in mind.

By the way, what makes you to be interested in this idea?

--Nomota.

2023년 9월 25일 (월) 00:22, BratishkaErik ***@***.***>님이 작성:

**Comment by BratishkaErik** [comment]
Just collecting languages on top of Zig with different syntaxes, I'd like to compare them and check how many positive and negative features of Zig are from syntax/spec/standard library, f.i. popular opinion "Zig makes allocations explicit by requiring to pass std.mem.Allocator" is a little bit misleading, as passing tmenrioned parameter is actually just a convention and you are not required to do so (compiler does not enforces you), so IMHO not quite fair to show it as syntax/spec feature etc.

Since (IIUC?) ZigC is focused on syntax changes, I can compare it with other extensions and main Zig language to see how many benefits remain from spec/standard library.

**Comment by BratishkaErik** [comment]
BTW another similar project which I find interesting: there is an alternative to standard library, made by a guy who finds it too bloat:
https://github.com/amp-59/zig_lib

He explicitly mentions that it is not ready (alpha-quality) yet, I'm writing it just in case you find it interesting too.

**Comment by ZigC-Lang** [comment]
Can I see the result of your collection? I just know of Bun.js only.

Actually I find it very difficult to formulate a language, much more than I
expected. My initial plan was to make a transpiler, and it turned out to be
far more complicated even to make a simple transpiler.

--Nomota

2023년 9월 25일 (월) 03:06, BratishkaErik ***@***.***>님이 작성:

**Pull request merged**
